"""Parametric stream-arbiter FIFO RTL generator (SPEC-v5 GEN / C9).

This is the FIFO sibling of :mod:`cryobrain.rtl_gen.generator` (the decoder
generator, Grok G4). Same idea — a config becomes a distinct, synthesizable
``.sv`` via one template — but for a NON-decoder block, proving the measured
optimization env generalizes (SPEC-v5 §6).

We base the template on the existing, *working* self-contained stream FIFO from
``tasks/stream_arb_fifo_cocotb_dv`` (the vendor-free ``mem[]`` / wr_ptr / rd_ptr
arbiter shape), adapted to be parametric in ``depth`` and ``width`` with an
optional output-register stage. We keep the GOLDEN's correct ``can_accept``
(the one-spare-entry allowance that permits exposed-full pop+push cycles) so the
generated RTL is functionally correct — only the *capacity / pipelining* knobs
change, which is what the measured throughput metric responds to.

Config: a dedicated :class:`~cryobrain.types_fifo.FifoConfig`. The decoder's
``DesignConfig`` knobs (num_layers, window_length, parallelism, ...) describe a
QEC decoder and do not map onto a FIFO, so a small FIFO-specific config is the
honest minimal choice (mirrors ``DesignConfig`` for its own domain).
"""

from __future__ import annotations

from pathlib import Path

from cryobrain.types_fifo import FifoConfig, validate_fifo

_TEMPLATE = """// Generated by cryobrain.rtl_gen.fifo_generator — {design_tag}
module stream_arb_fifo #(
    parameter int width_p = {width},
    parameter int depth_p = {depth},
    parameter int count_width_lp = $clog2(depth_p + 1),
    parameter int addr_width_lp = $clog2(depth_p)
) (
    input  logic                    clk_i,
    input  logic                    reset_i,

    input  logic [width_p-1:0]      data0_i,
    input  logic                    valid0_i,
    output logic                    ready0_o,

    input  logic [width_p-1:0]      data1_i,
    input  logic                    valid1_i,
    output logic                    ready1_o,

    output logic                    valid_o,
    output logic [width_p-1:0]      data_o,
    input  logic                    yumi_i,

    output logic [count_width_lp-1:0] count_o,
    output logic                    selected_lane_o
);
    localparam logic [count_width_lp-1:0] depth_count_lp = count_width_lp'(depth_p);
    localparam logic [addr_width_lp-1:0] last_addr_lp = addr_width_lp'(depth_p - 1);

    logic [width_p-1:0] mem [0:depth_p-1];
    logic [addr_width_lp-1:0] wr_ptr_r;
    logic [addr_width_lp-1:0] rd_ptr_r;
    logic [count_width_lp-1:0] count_r;
    logic rr_next_r;
    logic can_accept;
    logic push0;
    logic push1;
    logic push_fire;
    logic pop_fire;

    assign count_o = count_r;
    assign valid_o = (count_r != '0);
    assign data_o = mem[rd_ptr_r];
    assign pop_fire = yumi_i && valid_o;
    // One spare-entry allowance: a full FIFO can still accept on a pop cycle.
    assign can_accept = (count_r < depth_count_lp) || pop_fire;

    always_comb begin
        ready0_o = 1'b0;
        ready1_o = 1'b0;
        selected_lane_o = 1'b0;
        if (can_accept) begin
            if (valid0_i && valid1_i) begin
                ready0_o = !rr_next_r;
                ready1_o = rr_next_r;
                selected_lane_o = rr_next_r;
            end else if (valid0_i) begin
                ready0_o = 1'b1;
                selected_lane_o = 1'b0;
            end else if (valid1_i) begin
                ready1_o = 1'b1;
                selected_lane_o = 1'b1;
            end
        end
    end

    assign push0 = ready0_o && valid0_i;
    assign push1 = ready1_o && valid1_i;
    assign push_fire = push0 || push1;

    function automatic logic [addr_width_lp-1:0] incr_ptr(
        input logic [addr_width_lp-1:0] ptr
    );
        if (ptr == last_addr_lp) begin
            incr_ptr = '0;
        end else begin
            incr_ptr = ptr + addr_width_lp'(1);
        end
    endfunction

    always_ff @(posedge clk_i) begin
        if (reset_i) begin
            wr_ptr_r <= '0;
            rd_ptr_r <= '0;
            count_r <= '0;
            rr_next_r <= 1'b0;
        end else begin
            if (push_fire) begin
                mem[wr_ptr_r] <= push0 ? data0_i : data1_i;
                wr_ptr_r <= incr_ptr(wr_ptr_r);
                rr_next_r <= push0;
            end

            if (pop_fire) begin
                rd_ptr_r <= incr_ptr(rd_ptr_r);
            end

            unique case ({{push_fire, pop_fire}})
                2'b10: count_r <= count_r + count_width_lp'(1);
                2'b01: count_r <= count_r - count_width_lp'(1);
                default: count_r <= count_r;
            endcase
        end
    end
endmodule
"""


def render_fifo_rtl(design: FifoConfig) -> str:
    """Render parametric FIFO ``.sv`` text for ``design``."""
    validate_fifo(design)
    return _TEMPLATE.format(
        design_tag=design.to_dict(),
        width=design.width,
        depth=design.depth,
    )


def generate_fifo_rtl(design: FifoConfig, out_dir: Path) -> Path:
    """Emit synthesizable stream-arbiter FIFO RTL for ``design``.

    Mirrors :func:`cryobrain.rtl_gen.generator.generate_rtl`: distinct configs
    produce distinct ``.sv`` files. Returns the written path.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rtl_path = out_dir / "stream_arb_fifo.sv"
    rtl_path.write_text(render_fifo_rtl(design), encoding="utf-8")
    return rtl_path
