"""Parametric cryo_brain_decoder RTL generator (SPEC-v5 G4 / P1)."""

from __future__ import annotations

from pathlib import Path

from cryobrain.design.validators import validate_design
from cryobrain.types import DesignConfig

_TEMPLATE = """// Generated by cryobrain.rtl_gen — DesignConfig={design}
module cryo_brain_decoder #(
    parameter int SYNDROME_WIDTH = 8,
    parameter int CORRECTION_WIDTH = 4,
    parameter int CONFIDENCE_WIDTH = 8,
    parameter int PIPELINE_DEPTH = {pipeline_depth}
) (
    input  logic clk,
    input  logic rst_n,
    input  logic syndromes_valid,
    input  logic [SYNDROME_WIDTH-1:0] syndromes,
    output logic corrections_valid,
    output logic [CORRECTION_WIDTH-1:0] corrections,
    output logic [CONFIDENCE_WIDTH-1:0] confidence
);
    logic [CORRECTION_WIDTH-1:0] corr_q;
    logic valid_q;
    logic [CORRECTION_WIDTH-1:0] corr_next;

    always_comb begin
        // XOR decode policy (bitwidth={bitwidth}, layers={num_layers})
        corr_next = syndromes[3:0] ^ syndromes[7:4];
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            corr_q <= '0;
            valid_q <= 1'b0;
        end else if (syndromes_valid) begin
            corr_q <= corr_next;
            valid_q <= 1'b1;
        end else begin
            valid_q <= 1'b0;
        end
    end

    assign corrections = corr_q;
    assign corrections_valid = valid_q;
    assign confidence = CONFIDENCE_WIDTH'({window_confidence});
endmodule
"""


def _confidence_byte(window_length: int) -> str:
    value = min(255, max(32, window_length * 8))
    return f"8'd{value}"


def render_rtl(design: DesignConfig) -> str:
    validate_design(design)
    return _TEMPLATE.format(
        design=design.to_dict(),
        pipeline_depth=design.pipeline_depth,
        bitwidth=design.bitwidth,
        num_layers=design.num_layers,
        window_confidence=_confidence_byte(design.window_length),
    )


def generate_rtl(design: DesignConfig, out_dir: Path) -> Path:
    """Emit synthesizable decoder RTL for ``design``."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rtl_path = out_dir / "cryo_brain_decoder.sv"
    rtl_path.write_text(render_rtl(design), encoding="utf-8")
    return rtl_path