"""Parametric cryo_brain_decoder RTL generator (SPEC-v5 G4 / P1)."""

from __future__ import annotations

import shutil
from pathlib import Path

from cryobrain.design.config import GOLDEN_BASELINE
from cryobrain.design.validators import validate_design
from cryobrain.types import DesignConfig

_TASK_ROOT = Path(__file__).resolve().parents[2] / "tasks" / "cryo_brain_decoder"
_GOLDEN_RTL = _TASK_ROOT / "donotaccess" / "cryo_brain_decoder_golden.sv"

# Functional path matches golden.sv (L2 spine). Knobs add synthesis ballast only.
_TEMPLATE = """// Generated by cryobrain.rtl_gen — {design_tag}
module cryo_brain_decoder #(
    parameter int SYNDROME_WIDTH = 8,
    parameter int CORRECTION_WIDTH = 4,
    parameter int CONFIDENCE_WIDTH = 8,
    parameter int PIPELINE_DEPTH = {pipeline_depth},
    parameter int NUM_LAYERS = {num_layers},
    parameter int PARALLELISM = {parallelism}
) (
    input  logic clk,
    input  logic rst_n,
    input  logic syndromes_valid,
    input  logic [SYNDROME_WIDTH-1:0] syndromes,
    output logic corrections_valid,
    output logic [CORRECTION_WIDTH-1:0] corrections,
    output logic [CONFIDENCE_WIDTH-1:0] confidence
);
    logic [CORRECTION_WIDTH-1:0] corr_q;
    logic valid_q;
    logic [CORRECTION_WIDTH-1:0] decode_wire;
    logic [CORRECTION_WIDTH-1:0] layer_shadow [0:NUM_LAYERS-1];
    logic [CORRECTION_WIDTH-1:0] bank_shadow [0:PARALLELISM-1];
    logic [CORRECTION_WIDTH-1:0] pipe_shadow [0:PIPELINE_DEPTH-1];
    integer i;

    assign decode_wire = {golden_decode_expr};

    always_comb begin
        layer_shadow[0] = decode_wire;
        for (i = 1; i < NUM_LAYERS; i++) begin
            layer_shadow[i] = layer_shadow[i-1];
        end
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            corr_q <= '0;
            valid_q <= 1'b0;
            for (i = 0; i < PARALLELISM; i++) begin
                bank_shadow[i] <= '0;
            end
            for (i = 0; i < PIPELINE_DEPTH; i++) begin
                pipe_shadow[i] <= '0;
            end
        end else if (syndromes_valid) begin
            corr_q <= decode_wire;
            valid_q <= 1'b1;
            for (i = 0; i < PARALLELISM; i++) begin
                bank_shadow[i] <= decode_wire ^ syndromes[CORRECTION_WIDTH-1:0];
            end
            pipe_shadow[0] <= layer_shadow[NUM_LAYERS-1];
            for (i = 1; i < PIPELINE_DEPTH; i++) begin
                pipe_shadow[i] <= pipe_shadow[i-1];
            end
        end else begin
            valid_q <= 1'b0;
        end
    end

    assign corrections = corr_q;
    assign corrections_valid = valid_q;
    assign confidence = CONFIDENCE_WIDTH'({window_confidence});
endmodule
"""


def _golden_decode_expr() -> str:
    """Measured L2 spine: same XOR decode as cryo_brain_decoder_golden.sv."""
    return "syndromes[3:0] ^ syndromes[7:4]"


def _confidence_byte(window_length: int) -> str:
    value = min(255, max(32, window_length * 8))
    return f"8'd{value}"


def render_rtl(design: DesignConfig) -> str:
    validate_design(design)
    return _TEMPLATE.format(
        design_tag=design.to_dict(),
        pipeline_depth=max(1, design.pipeline_depth),
        num_layers=max(1, design.num_layers),
        parallelism=max(1, design.parallelism),
        golden_decode_expr=_golden_decode_expr(),
        window_confidence=_confidence_byte(design.window_length),
    )


def generate_rtl(design: DesignConfig, out_dir: Path) -> Path:
    """Emit synthesizable decoder RTL for ``design``."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rtl_path = out_dir / "cryo_brain_decoder.sv"
    if design == GOLDEN_BASELINE and _GOLDEN_RTL.is_file():
        shutil.copy2(_GOLDEN_RTL, rtl_path)
        return rtl_path
    rtl_path.write_text(render_rtl(design), encoding="utf-8")
    return rtl_path