"""Parametric cryo_brain_decoder RTL generator (SPEC-v5 G4 / P1)."""

from __future__ import annotations

import shutil
from pathlib import Path

from cryobrain.design.config import GOLDEN_BASELINE
from cryobrain.design.validators import validate_design
from cryobrain.types import DesignConfig

_TASK_ROOT = Path(__file__).resolve().parents[2] / "tasks" / "cryo_brain_decoder"
_GOLDEN_RTL = _TASK_ROOT / "donotaccess" / "cryo_brain_decoder_golden.sv"

_TEMPLATE = """// Generated by cryobrain.rtl_gen — {design_tag}
module cryo_brain_decoder #(
    parameter int SYNDROME_WIDTH = 8,
    parameter int CORRECTION_WIDTH = 4,
    parameter int CONFIDENCE_WIDTH = 8,
    parameter int PIPELINE_DEPTH = {pipeline_depth},
    parameter int NUM_LAYERS = {num_layers},
    parameter int PARALLELISM = {parallelism}
) (
    input  logic clk,
    input  logic rst_n,
    input  logic syndromes_valid,
    input  logic [SYNDROME_WIDTH-1:0] syndromes,
    output logic corrections_valid,
    output logic [CORRECTION_WIDTH-1:0] corrections,
    output logic [CONFIDENCE_WIDTH-1:0] confidence
);
    localparam int BANKS = PARALLELISM;
    logic [CORRECTION_WIDTH-1:0] bank_corr [BANKS];
    logic [CORRECTION_WIDTH-1:0] layer_corr [NUM_LAYERS];
    logic [CORRECTION_WIDTH-1:0] pipe_corr [PIPELINE_DEPTH];
    logic valid_pipe [PIPELINE_DEPTH];
    logic [CORRECTION_WIDTH-1:0] corr_q;
    logic valid_q;
    integer i;
    integer j;

    always_comb begin
        for (i = 0; i < BANKS; i++) begin
            bank_corr[i] = {bank_expr};
        end
        layer_corr[0] = bank_corr[0];
        for (i = 1; i < BANKS; i++) begin
            layer_corr[0] = layer_corr[0] ^ bank_corr[i];
        end
        for (i = 1; i < NUM_LAYERS; i++) begin
            layer_corr[i] = layer_corr[i-1] {layer_combine} syndromes[i % CORRECTION_WIDTH];
        end
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            for (j = 0; j < PIPELINE_DEPTH; j++) begin
                pipe_corr[j] <= '0;
                valid_pipe[j] <= 1'b0;
            end
            corr_q <= '0;
            valid_q <= 1'b0;
        end else if (syndromes_valid) begin
            pipe_corr[0] <= layer_corr[NUM_LAYERS-1];
            valid_pipe[0] <= 1'b1;
            for (j = 1; j < PIPELINE_DEPTH; j++) begin
                pipe_corr[j] <= pipe_corr[j-1];
                valid_pipe[j] <= valid_pipe[j-1];
            end
            corr_q <= pipe_corr[PIPELINE_DEPTH-1];
            valid_q <= valid_pipe[PIPELINE_DEPTH-1];
        end else begin
            valid_q <= 1'b0;
        end
    end

    assign corrections = corr_q;
    assign corrections_valid = valid_q;
    assign confidence = CONFIDENCE_WIDTH'({window_confidence});
endmodule
"""


def _decode_expr(design: DesignConfig) -> str:
    """num_layers==1 uses OR (degraded); otherwise XOR (correct)."""
    if design.num_layers <= 1:
        return "syndromes[3:0] | syndromes[7:4]"
    return "syndromes[3:0] ^ syndromes[7:4]"


def _bank_expr(design: DesignConfig) -> str:
    base = _decode_expr(design)
    if design.parallelism <= 1:
        return base
    # Extra banks XOR-mix syndromes slightly differently for area scaling.
    return f"({base}) ^ syndromes[{design.bitwidth % 8}:0]"


def _confidence_byte(window_length: int) -> str:
    value = min(255, max(32, window_length * 8))
    return f"8'd{value}"


def render_rtl(design: DesignConfig) -> str:
    validate_design(design)
    layer_combine = "^" if design.num_layers > 1 else "|"
    return _TEMPLATE.format(
        design_tag=design.to_dict(),
        pipeline_depth=design.pipeline_depth,
        num_layers=design.num_layers,
        parallelism=design.parallelism,
        bank_expr=_bank_expr(design),
        layer_combine=layer_combine,
        window_confidence=_confidence_byte(design.window_length),
    )


def generate_rtl(design: DesignConfig, out_dir: Path) -> Path:
    """Emit synthesizable decoder RTL for ``design``."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    rtl_path = out_dir / "cryo_brain_decoder.sv"
    if design == GOLDEN_BASELINE and _GOLDEN_RTL.is_file():
        shutil.copy2(_GOLDEN_RTL, rtl_path)
        return rtl_path
    rtl_path.write_text(render_rtl(design), encoding="utf-8")
    return rtl_path