// Generated by cryobrain.rtl_gen — {'bitwidth': 4, 'num_layers': 2, 'parallelism': 4, 'pipeline_depth': 2, 'window_length': 8}
module cryo_brain_decoder #(
    parameter int SYNDROME_WIDTH = 8,
    parameter int CORRECTION_WIDTH = 4,
    parameter int CONFIDENCE_WIDTH = 8,
    parameter int PIPELINE_DEPTH = 2,
    parameter int NUM_LAYERS = 2,
    parameter int PARALLELISM = 4
) (
    input  logic clk,
    input  logic rst_n,
    input  logic syndromes_valid,
    input  logic [SYNDROME_WIDTH-1:0] syndromes,
    output logic corrections_valid,
    output logic [CORRECTION_WIDTH-1:0] corrections,
    output logic [CONFIDENCE_WIDTH-1:0] confidence
);
    logic [CORRECTION_WIDTH-1:0] corr_q;
    logic valid_q;
    logic [CORRECTION_WIDTH-1:0] decode_wire;
    logic [CORRECTION_WIDTH-1:0] layer_shadow [0:NUM_LAYERS-1];
    logic [CORRECTION_WIDTH-1:0] bank_shadow [0:PARALLELISM-1];
    logic [CORRECTION_WIDTH-1:0] pipe_shadow [0:PIPELINE_DEPTH-1];
    integer i;

    assign decode_wire = syndromes[3:0] ^ syndromes[7:4];

    always_comb begin
        layer_shadow[0] = decode_wire;
        for (i = 1; i < NUM_LAYERS; i++) begin
            layer_shadow[i] = layer_shadow[i-1];
        end
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            corr_q <= '0;
            valid_q <= 1'b0;
            for (i = 0; i < PARALLELISM; i++) begin
                bank_shadow[i] <= '0;
            end
            for (i = 0; i < PIPELINE_DEPTH; i++) begin
                pipe_shadow[i] <= '0;
            end
        end else if (syndromes_valid) begin
            corr_q <= decode_wire;
            valid_q <= 1'b1;
            for (i = 0; i < PARALLELISM; i++) begin
                bank_shadow[i] <= decode_wire ^ syndromes[CORRECTION_WIDTH-1:0];
            end
            pipe_shadow[0] <= layer_shadow[NUM_LAYERS-1];
            for (i = 1; i < PIPELINE_DEPTH; i++) begin
                pipe_shadow[i] <= pipe_shadow[i-1];
            end
        end else begin
            valid_q <= 1'b0;
        end
    end

    assign corrections = corr_q;
    assign corrections_valid = valid_q;
    assign confidence = CONFIDENCE_WIDTH'(8'd64);
endmodule
